services:
  keycloak:
    image: keycloak
    container_name: keycloak
    command: ["export",
      "--db=postgres",
      "--db-url=jdbc:postgresql://postgres:5432/keycloak",
      "--db-username=keycloak",
      "--db-password=keycloak",
      "--realm=demo",
      "--dir=/export",
      "--users=same_file"
      ]
    volumes:
      - ./target/export:/export

