services:
  postgres:
    container_name: postgres
    image: postgres:16-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./postgres/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    environment:
      - POSTGRES_PASSWORD=demo
      - POSTGRES_USER=demo
      - POSTGRES_DB=demo
    healthcheck:
          test: pg_isready --dbname=keycloak --username=keycloak
          interval: 40s
          timeout: 30s
          retries: 3
          start_period: 10s
  keycloak:
    container_name: keycloak
    image: keycloak
    command: ["start-dev",
      "--db=postgres",
      "--db-url=jdbc:postgresql://postgres:5432/keycloak",
      "--db-username=keycloak",
      "--db-password=keycloak",
      "--http-enabled=true",
      "--health-enabled=true",
      "--metrics-enabled=true"
      ]
    depends_on:
      postgres:
          condition: service_healthy
    ports:
      - 8000:8080
    healthcheck:
      test: timeout 10s bash -c ':> /dev/tcp/localhost/8080'
      interval: 40s
      timeout: 30s
      retries: 3
      start_period: 30s
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=password
  backend:
    container_name: backend
    image: backend
    depends_on:
      keycloak:
        condition: service_healthy
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=postgres://demo:demo@postgres/demo
      - PUBLIC_KEY=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0vtKuQx4Y7vn+O59uGIAINc99IS5w+EXsbzwBBS5iIukSnYM5eI5XRINTtM0+SIhg2HH7zJ5dE1m1eKj+84VfgQwBdsYZkSg+J7MvaHIADba/v7no2RKaYKZCI6CjwFzioYP3EtF3xuwOFoitr/7sn8MmtmkKrMUpCjuikaDyFxuSJ26GHK9cco60QXHqRw4R8K0Eg5/8zryDDFi86eepsV/ZwoBhEj4QnMVwOs8XzPE/9kZOn0xbEhHt2hMCREqq3QG4EovLyUTrdDRIdDL9eIv7yO4I9Yce4zBCitidq6JwHUcZR5Sa3QhyXg5Vt29OW2enhq5o892mvmbD/MeMwIDAQAB
  nginx:
    container_name: www
    image: www
    ports:
      - 4200:80
    healthcheck:
      test: curl --fail --head -fsS http://localhost || exit 1
      interval: 40s
      timeout: 30s
      retries: 2
      start_period: 10s
    depends_on:
      keycloak:
        condition: service_healthy
      backend:
        condition: service_healthy
volumes:
  postgres: