apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: keycloak
  name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      run: keycloak
  template:
    metadata:
      labels:
        run: keycloak
    spec:
      containers:
      - name: keycloak
        image: ghcr.io/arge3d-cad/arge3d-keycloak
        imagePullPolicy: Always
        #command: ["/opt/keycloak/bin/kc.sh", "start-dev", "--proxy", "edge", "--features=declarative-user-profile", "--spi-x509cert-lookup-haproxy-trust-proxy-verification=true"]
        # kubectl port-forward key... 8000:8080 for admin - ui
        command: ["/opt/keycloak/bin/kc.sh", "start-dev", "--proxy", "edge", "--features=declarative-user-profile", "--spi-x509cert-lookup-haproxy-trust-proxy-verification=true", "--hostname-admin-url=http://localhost:8000", "--log-level=INFO" ]
       
        ports:
        - containerPort: 8080
          name: http
        readinessProbe:
          httpGet:
            httpHeaders:
              - name: Accept
                value: application/json          
            path: /health/ready
            port: http
          initialDelaySeconds: 60
        livenessProbe:
          httpGet:
            httpHeaders:
              - name: Accept
                value: application/json          
            path: health/live
            port: http
          initialDelaySeconds: 180
        env:
          - name: KEYCLOAK_ADMIN
            valueFrom:
              configMapKeyRef:
                name: keycloak-credentials
                key: username
          - name: KEYCLOAK_ADMIN_PASSWORD
            value: admiot.4digipro
          - name: KC_DB
            value: postgres
          - name: KC_DB_USERNAME
            valueFrom:
              configMapKeyRef:
                name: keycloak-credentials
                key: dbuser
          - name: KC_DB_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: keycloak-credentials
                key: dbpassword
          - name: KC_DB_URL_HOST
            value: postgres
          - name: KC_DB_URL_DATABASE
            value: keycloak
          - name: KC_HOSTNAME_URL
            #value: http://localhost:8000
            value: https://auth.cloud.arge3d.at
            #value: https://auth.cloud.key.fit
          - name: KC_HOSTNAME_STRICT
            value: "false"
          - name: KC_HOSTNAME_STRICT_HTTPS
            value: "false"
          - name: KC_HTTP_ENABLED
            value: "true"
          - name: KC_HTTP_PORT
            value: "8080"
          - name: KC_LOG_LEVEL
            value: INFO
          - name: keycloak.profile.feature.upload_scripts
            value: enabled
          - name: KC_HEALTH_ENABLED
            value: "true"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-credentials
data:
  username: administrator
  dbuser: keycloak
  dbpassword: keycloak
  dbvendor: postgres