###
# @import ./login.http
# @ref login
###
GET {{BASE}}/users/posts
Authorization: Bearer {{login.access_token}}
Accept: application/json
###
# @name addpost-without-userid
PUT {{BASE}}/users/posts
Authorization: Bearer {{login.access_token}}
Content-Type: application/json

{
    "title": "my new post",
    "body": "This shows how to append a post",
    "published": true
}

?? status == 400
###
GET {{BASE}}/users/posts
Authorization: Bearer {{login.access_token}}
Accept: text/csv
###
# @name me
GET {{BASE}}/users/i
Authorization: Bearer {{login.access_token}}
Accept: application/json

?? status == 200
###
# @name import
POST {{BASE}}/portation/xlsx
Accept: application/json
Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet

< ./import/import.xlsx
?? status == 200
###
# @name export
# @no-log
GET {{BASE}}/portation/xlsx
Accept: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet

{{ 
    response.body = "...skip binary..."
    delete response.rawHeaders
    console.log("=== export again ===")
    console.log(response)
}}
?? status == 200
###
