# docker compose file for our standalone postgres database
services:
    postgres:
        container_name: postgres
        image: postgres:16-alpine
        ports:
            - 5432:5432
        volumes:
            - postgres:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=keycloak
            - POSTGRES_USER=keycloak
            - POSTGRES_DB=keycloak
        healthcheck:
            test: pg_isready --dbname=keycloak --username=keycloak
            interval: 5s
volumes:
    postgres:
