@REALM={{$dotenv realm}}
@KEYCLOAK_URL=https://auth.htl-leonding.ac.at/
@TOKEN_ENDPOINT={{wellknown.response.body.token_endpoint}}
@AUTHORIZATION_ENDPOINT={{wellknown.response.body.authorization_endpoint}}
@ISSUER={{wellknown.response.body.issuer}}

# @name wellknown
GET {{KEYCLOAK_URL}}/realms/{{REALM}}/.well-known/openid-configuration
###
# @name issuer
GET {{ISSUER}}
Accept: application/json
###

# @name code
GET {{AUTHORIZATION_ENDPOINT}}?response_type=code&client_id=frontend&state=initial&redirect_uri=http%3A%2F%2Flocalhost%3A4200
###
